### ISSUE TITLE
partial backup

### ISSUE THREAD

**Issue by pishgaman-org** [psamim/telegram-cli-backup#10]
Hi and thanks for your script.
I want to backup my profile every day; but in this way it takes a lot of times, because I'm member of many groups.
can you add partial backup ability to your script?

**Comment by psamim** [comment]
I do not recommend this for your usage. You can use telegram-cli and your own script to get every message and add messages to your database on every message. You can modify the script for your self.

**Comment by psamim** [comment]
@pishgaman-org I can help writing an script for your needs if you need to.

**Comment by pishgaman-org** [comment]
Thanks.
I used another script and modified it myself.
