### ISSUE TITLE
No public keys found

### ISSUE THREAD

**Issue by mimre25** [psamim/telegram-cli-backup#13]
Hi,

when running your script (../tg/bin/telegram-cli -s backup.lua), I just get
" **\* No public keys found" 
after the configuration shown.

Is there something I'm doing wrong?

Do you need more information?

Cheers

**Comment by psamim** [comment]
Hi,

This is not about this script. You have not set up telegram-cli completely. Before using this script make sure telegram-cli itself can be run and is connected to you account. You have not added the public keys needed.

**Comment by mimre25** [comment]
Hi, thanks for the fast reply :)

Well I already used telegram-cli normally and had some chats via it. so I'm not sure where I'm wrong here.

**Comment by psamim** [comment]
@SquweeZ https://github.com/vysheng/tg/issues/796

**Comment by mimre25** [comment]
thanks, it works now!
