### ISSUE TITLE
Module 'lsqlite3' not found - version mismatch

### ISSUE THREAD

**Issue by Liliz** [psamim/telegram-cli-backup#2]
Hi, after installing lua and sqlite3 (using luarocks) I get the output below.
Looks like the script is looking for lsqlite3.so in /usr/local/share/lua/5.2 but it was actually installed in /usr/local/share/lua/5.1. Lua version is 5.2.

How can I make the script look for the right path or version?

**\* lua: backup.lua:53: module 'lsqlite3' not found:
    no field package.preload['lsqlite3']
    no file '/usr/local/share/lua/5.2/lsqlite3.lua'
    no file '/usr/local/share/lua/5.2/lsqlite3/init.lua'
    no file '/usr/local/lib/lua/5.2/lsqlite3.lua'
    no file '/usr/local/lib/lua/5.2/lsqlite3/init.lua'
    no file '/usr/share/lua/5.2/lsqlite3.lua'
    no file '/usr/share/lua/5.2/lsqlite3/init.lua'
    no file './lsqlite3.lua'
    no file '/usr/local/lib/lua/5.2/lsqlite3.so'
    no file '/usr/lib/x86_64-linux-gnu/lua/5.2/lsqlite3.so'
    no file '/usr/lib/lua/5.2/lsqlite3.so'
    no file '/usr/local/lib/lua/5.2/loadall.so'
    no file './lsqlite3.so'

**Comment by psamim** [comment]
@Liliz 
You can modify the path Lua looks for packages using $LUA_PATH environment variable, as described here, http://www.lua.org/manual/5.2/manual.html#pdf-package.path .

And if you compile Luarocks, I think it is possible to modify the version and the path, https://github.com/keplerproject/luarocks/wiki/Installation-instructions-for-Unix .

Also you did not mention your Linux distro. I think `luarocks` package in Ubuntu 14.04 is outdated and works with Lua 5.1, not 5.2. If you are using Ubuntu, you can either run my script with Lua 5.1 (which I have not tested) or compile Luarocks yourself. 

I have tested it with Lua 5.3 with the latest Luarocks on Arch Linux.

**Comment by Liliz** [comment]
Solved, thank you! Compliling Luarocks worked perfectly on Ubuntu 14.04

First I removed the packaged version of luarocks (5.1) and then installed the new one from source; it had already the correct version number (5.2) and path.
