### ISSUE TITLE
How do I start the script?

### ISSUE THREAD

**Issue by Ad-Blokker** [psamim/telegram-cli-backup#4]
I know that I am kinda a noob but if I try to start the "telegram-cli -s backup.lua" command it gives me the error: telegram-cli: command not found
What do I do wrong?
Can you give me a detailed guide on how to start the script

I have lua installed and telegram-cli

**Comment by psamim** [comment]
How do you start telegram-cli? Just do that and append "-s backup.lua" to it. Also "backup.lua" should point to the actual file (backup.lua) so you may have to give relative addresses (like /home/backup.lua).

**Comment by Ad-Blokker** [comment]
I am probaly a big noob but I can't get it working :(
Sorry for bothering you but can you say what I do wrong
(btw sorry my ubuntu is in Dutch)

![noob](https://cloud.githubusercontent.com/assets/14195799/9789606/6babf1fa-57d1-11e5-8665-e31bf4f0a55d.JPG)

**Comment by Ad-Blokker** [comment]
Owh now it says i need to install lsqlite, but I can't find the package anywhere :/
![lsqlite](https://cloud.githubusercontent.com/assets/14195799/9794090/7ad14ac8-57e9-11e5-878d-789163630186.JPG)

**Comment by psamim** [comment]
First install luarocks, then `luarocks install lsqlite3`.

**Comment by psamim** [comment]
Can this issue be closed?

**Comment by Ad-Blokker** [comment]
Ow sorry, yes it can be closed!
Yhanks for your help!
