### ISSUE TITLE
Never executed

### ISSUE THREAD

**Issue by sospedra** [psamim/telegram-cli-backup#7]
I've tried properly everything: sqlite3 by using luarocks, the tg client and getted the script.

Then I execute the following:
`bin/telegram-cli -s bin/backup.lua`

And it executes the telegram-cli but not the script: there's no info in the sqlite nor print the "done". So, I assume that's not doing nothing.

Any idea?

**Comment by psamim** [comment]
@edravis 
You can use print in different parts of the script to debug and find the problem, also check if the sqlite database file is correctly created.
